- name: "installing nginx"
  hosts: web
  tasks:
  - name:
    ansible.builtin.package:
      name: nginx
      state: nginx
  
  - name:
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes