- name : "using play level variable in tasks"
  hosts:  web
  become : yes
  vars:
    course: "devops"
    duration: "120hrs"
    trainer_name: "suresh"
  tasks:
  - name: "using vriables"
    ansible.builtin.debug:
      msg: "i am learing {{course}} with {{duration}} , trainer name is {{trainer_name}}"




