- name: 
  hosts: web
  vars:
    course: "devops"
    duration: "129hrs"
    trainer: "suresh"
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "course is {{ course }} with {{ duration }} duration , trainer {{ trainer }}"
