- name: accessing variables from varfiles
  hosts: web
  become: yes
  vars_files:
    vars.yaml
  tasks:
  - name: "accessing variables from var_files"
    ansible.builtin.debug:
      msg: "i am learning {{ course }} with {{ duration }}, trainer names is {{trainer_name}}"














  