- name: 
  hosts: web
  vars:
    course: "devops"
    duration: "129hrs"
    trainer: "suresh"
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "course is {{ course }} with {{ duraion }} duration , trainer {{ trainer }}"

  - name:
    vars:
      course: "devops"
      duration: "4hrs"
      trainer: "siva"
    ansible.builtin.debug:
      msg: "course is {{ course }} with {{ duraion }} duration , trainer {{ trainer }}"
