- name: "vars_prompt"
  hosts: web
  vars:
  - name: course
    prompt: "what is your course name"
    private: false
  - name: durations
    prompt: "durations"
    private: false
  - name: trainer
    prompt: "trainer name"
    private: false
  tasks:
  - name: "printing the details"
    ansible.builtin.debug:
      msg: "{{ course }}- {{ durations }} - {{ trainer }}"
