- name: "accessing variables from prompt"
  hosts: web
  become: yes
  vars_prompt:
  - name: "course"
    prompt: "enter the course name"
    private : false
  - name: "duration"
    prompt: "enter the duration time"
    private: false
  - name: "trainer_name"
    prompt: "enter the trainer name"
    private: false

  tasks:
  - name: "accessing vars from prompt"
    ansible.builtin.debug:
      msg: "i am learning {{course}} with {{duration}} trainer_name is {{trainer_name}}"



