- name: "variables from prompt"
  hosts: web
  vars_prompt:
  - name: "COURSE"
    prompt: "please enter your course name"
  - name: "Duration"
    prompt: "please enter the duration of course"
  - name: "TRAINER NAME"
    prompt: "please enter tht trainer naame"
  tasks:
  - name: printing the course information
    ansible.builtin.debug:
      msg: " hii, i am learning {{COURSE}} with a duration of {{DURATION}}. trainer name is "

- name: printing variables from prompt
  hosts: web
  vars_prompt:
  - name: "course"
    prompt: "enter your course name"
    private: false
  - name: "duration"
    prompt: "enter your course duration time"
    private: false
  - name: "trainer_names"
    prompt: "enter your trainer name"
    private: false
  tasks:
  - name: printing variables from prompt
    ansible.builtin.debug:
    msg: "hii, iam learning {{course}} with a duration of {{duration}}. trainer name is {{trainer_names}}"

    