- name: "vars_prompt"
  hosts: web
  vars:
  - name: "course_name"
    prompt: "what is your course name"
    private: false
  - name: "duration"
    prompt: "duration"
    private: false
  - name: "trainer_name"
    prompt: "trainer name"
    private: false
  tasks:
  - name: "printing the details"
    ansible.builtin.debug:
      msg: "{{ course_name }}- {{ duration }} - {{ trainer_name }}"
