- name:
  hosts: web
  vars_prompt:
  - name: course
    prompt: "enter the course name"
    private: false
  - name: duration:
    prompt: "enter the duration time"
    private: false
  - name: trainer:
    prompt: "enter the trainer name"
    private: false
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "{{ course }} {{ duraion }} {{ trainer }}"


