- name: printing variables from prompt
  hosts: web
  vars_prompt:
  - name: "course"
    prompt: "enter your course name"
    private: false
  - name: "duration"
    prompt: "enter your course duration time"
    private: false
  - name: "trainer_names"
    prompt: "enter your trainer name"
    private: false
  tasks:
  - name: printing variables from prompt
    ansible.builtin.debug:
      msg: "hii, iam learning {{course}} with a duration of {{duration}}. trainer name is {{trainer_names}}"

    