- name: vars from args,tasks,prompt,play,inv,files
  hosts: web
  vars_files:
  - vars.yaml
  vars:
    COURSE: "backend technologies from play files"
    DURATION: "150hrs"
    TRAINER: "P.Suresh Gopi"
  vars_prompt:
    - name:
      prompt: "ENTER THE COURSE NAME"
      private: false
    - name:
      prompt: "ENTER THE DURATION OF COURSE"
      private: false
    - name:
      prompt: "ENTER THE TRAINER NAME"
      private: false

  
  tasks:
  - name: "vars from args,tasks,prompt,play,inv,files"
    vars:
      COURSE: "backend technologies from task files"
      DURATION: "150hrs"
      TRAINER: "P.Suresh Gopi"
      ansible.builtin.debug:
        msg: "hii, i am learning {{COURSE}} with a duration of {{DURATION}}, Trainer name is {{TRAINER}}"
