- name:
  hosts: local
  connection: local
  vars:
    course: "devops"
    duration: "120hrs"
    trainer: "siva"
    topics:
    - ansible
    - nginx
    - postfix
    live: true
    tools:
      name: "suresh"
      son: "khanishk"
      wife: "hema"
  tasks:
  - name:
    ansible.builtin.debug:
      msg: ""