- name:
  hosts: local
  connection: local
  vars:
    number: 2
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "print if number is less than 2"
    when: number | int > 10
  - name:
    ansible.builtin.debug:
      msg: "print if number is less than 2"
    when: number | int < 10