- name: conditions greater than less than
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: "enter the my_number"
    private: false
  tasks:
  - name: print if my_number less than 10
    ansible.builtin.debug:
      msg: "the given my_number {{my_number}} is less than 10"
    when: my_number < 10
  
  - name: print if my_number greater than 10
    ansible.builtin.debug:
      msg: "the given my_number {{my_number}} is greater than 10"
    when: my_number >= 10
