- name: "number"
  hosts: local
  connection: local
  vars_prompt:
    name: "number"
    prompt: "enter the number"
    private: false
  tasks: 
  - name: " number >  10"
    ansible.builtin.debug:
      msg: "the number is less than 10"
    when: number | int > 10
  - name: "number < 10"
    ansible.builtin.debug:
      msg: "the number is greater than 10"
    when: number | int < 10

  