- name: "test condition"
  hosts: web
  vars:
  - number: 9
  tasks:
  - name: "print number"
    ansible.builtin.debug:
      msg: " number is grater than 10 "
    when: number | int > 10 
  - name: "print number"
    ansible.builtin.debug:
      msg: " number is less than 10 "
    when: number | int < 10