- name: conditions greater than less than
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: "enter the number"
    private: false
  tasks:
  - name: print if number less than 10
    ansible.builtin.debug:
      msg: "the given number {{number}} is less than 10"
    when: number < 10
  
  - name: print if number greater than 10
    ansible.builtin.debug:
      msg: "the given number {{number}} is greater than 10"
    when: number >= 10
