- name:
  hosts: web
  become: yes
  tasks:
  - name: "check user exists or not"
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true

  - name: "checking"
    ansible.builtin.command: useradd expense
    when: user.rc != 0

  - name: "check"
    ansible.builtin.debug:
      msg: "{{user}}"
