- name:
  hosts: web
  become: yes
  tasks:
  - name:
    ansible.builtin.command: id expense
    register: user
    ignore_errors: True

  - name:
    ansible.builtin.command: useradd expense
    when: user.rc != 0

  - name:
    ansible.builtin.debug:
      msg: "{{user}}"