- name: 
  hosts: web
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}""
  - name:
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Installing Nginx on Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_facts['os_family'] == "Debian"