- name: loops 
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loops:
    - { name: 'nginx' , state: 'present'}
