- name:
  hosts: web
  tasks:
  - name:
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      { name: "mysql" , state: "present" }
      { name: "postfix" , state: "present" }
