- name: intalling packages from loops
  hosts: web 
  become: yes

  tasks:
  - name:
    ansible.builtin.package:
      name: "{{item}}"
      state: present
      msg: " installing {{ item }} "
    loop:
    - mysql
    - git