- name: installing packages from loops
  hosts: web
  tasks:
  - name:
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loops:
    - {name: 'nginx', state: 'absent'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'postfix', state: 'absent'}