- name:
  hosts: local
  connection: local
  tasks:
  - name: 
    ansible.builtin.debug:
      msg: "course {{ course | default('ansible') }}"
  
  - name: 
    vars:
      greetings: "hii khani"
    ansible.builtin.debug:
      msg: "{{ greetings | uppper }}"
  
  - name: 
    vars:
      greetings: "hii khani"
    ansible.builtin.debug:
      msg: "{{ greetings | lower }}"

  - name:
    vars:
      list: [1,2,3,4,4,3,2,1]
    ansible.builtin.debug:
      msg: "{{ list | unique }}"
  
  - name:
    vars:
      list: [1,2,3,4,4,3,2,1]
    ansible.builtin.debug:
      msg: "{{ list | max }}"
  
  - name:
    vars:
      list: [1,2,3,4,4,3,2,1]
    ansible.builtin.debug:
      msg: "{{ list | min }}"
  
  - name:
    vars:
      item:
        course: "aws"
        trainer: "siva"
        duration: "120hrs"
    ansible.builtin.debug:
      msg: "{{ item | dict2items }}"

  - name:
    vars:
      course:
      - { "key": "name" , "value": "suresh" }
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"