- name:
  hosts: local
  connection: local
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "course: {{ course | default('Ansible') }}"
  
  - name:
    vars:
      greetings: "hii ramesh"
    ansible.builtin.debug:
      msg: " {{ greetings | upper }} "

  - name:
    vars:
      greetings: "hii ramesh"
    ansible.builtin.debug:
      msg: "{{ greetings | lower }}"
  
  - name:
    vars:
      numberss: [1,2,3,4,5,1,3,5,6]
    ansible.builtin.debug:
      msg: "{{ numberss | unique }}"
  
  - name:
    vars:
      nums: [12,34,56,6,343,243,2,53,25,]
    ansible.builtin.debug:
      msg: " {{ nums | min }} "
  
  - name:
    vars:
      nums: [12,34,56,6,343,243,2,53,25,]
    ansible.builtin.debug:
      msg: " {{ nums | max }} "
  
  