- name: creating ec2_instances and route53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-082da38ee3dde10b0"
    instance_type: "t3.micro"
    securitygp_id: "sg-0d53b673bc770d04c"
    amd_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: "khanishkcosmetics.store"
  tasks:
  - name: creating ec2_instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ securitygp_id }}"
      image_id: "{{ amd_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
  
  - name: printing the information
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"
  
  - name: creating route53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: creating route53 public records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"
  