- name: creating ec2_instances and r53 using ansible
  hosts: local
  connection: local 
  vars:
    subnet_id: "subnet-082da38ee3dde10b0"
    instances_type: "t3.micro"
    securitygroup_id: "sg-0d53b673bc770d04c"
    img_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - frontend
    - backend
    zone: "khanishkcosmetics.store"
  tasks:
  - name: creating ec2_instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"  
      instance_type: "{{ instances_type }}"
      security_group: "{{ securitygroup_id }}"
      image_id: "{{ img_id }}"
    loop: "{{ instances }}"
    register: ec2_instancess

  - name: creating s53 
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ ec2_instancess.results[0].private_ip_address }}"
      wait: true 
      overwrite: true