- name: creating ec2_instances and route53 records
  hosts: local
  connection: local
  vars:
    sg_id: "sg-0d53b673bc770d04c"
    subnet_id: "subnet-082da38ee3dde10b0"
    instances_type: "t3.micro"
    amd_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - frontend
    - backend
    ec2_inst:
    - ansible-node
  tasks:
  - name: creating ec2_instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instances_type }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ amd_id }}"
    loop: "{{ instances }}"
    register: ec2_instances 
  
  - name: printing the information
    ansible.builtin.debug:
      msg: " ec2_instances "
  