- name: creating ec2_instances and route53 records
  hosts: local
  connection: local 
  vars:
    subnet_id: "subnet-082da38ee3dde10b0"
    instances_type: "t3.micro"
    sg_id: "sg-0d53b673bc770d04c"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - frontend
    - backend
    zone: "khanishkcosmetics.store "
  tasks:
  - name: creating ec2_instances
    ansible.builtin.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instances_type }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instancees
  
  - name: creating route53 records
    ansible.builtin.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ec2_instancees}}"